"use client";

import { Fragment, useActionState, useRef, useState } from "react";
import { deleteSale, saveSales } from "@/app/actions/sales";

type Option = { id: string; name: string };
type SaleItem = { number: string; amount: number; rule_type: string };
type Sale = { id: string; receipt_number: number; raw_input: string; total_amount: number; created_at: string; items: SaleItem[] };

const formatMoney = (amount: number) => new Intl.NumberFormat("en-US").format(Math.round(amount));

export default function SalesEntry({ commissions, periods, sales, numberTotals }: { commissions: Option[]; periods: Option[]; sales: Sale[]; numberTotals: Record<string, number> }) {
  const [state, formAction] = useActionState(saveSales, {});
  const [prefix, setPrefix] = useState(0);
  const [rawInput, setRawInput] = useState("");
  const [expandedSales, setExpandedSales] = useState<Set<string>>(new Set());
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const formRef = useRef<HTMLFormElement>(null);
  const numbers = Array.from({ length: 100 }, (_, index) => `${prefix}${String(index).padStart(2, "0")}`);
  const addNumberToInput = (number: string) => {
    const nextValue = rawInput ? `${rawInput.replace(/\s*$/, "")}\n${number} ` : `${number} `;
    setRawInput(nextValue);
    requestAnimationFrame(() => { inputRef.current?.focus(); inputRef.current?.setSelectionRange(nextValue.length, nextValue.length); });
  };
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(360px,.8fr)]">
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-medium text-blue-700">အရောင်းစာရင်း</p><h2 className="text-xl font-bold">စာရင်းထည့်ရန်</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-700">{sales.length} စာရင်း</span></div>
      <form ref={formRef} action={formAction} className="space-y-4">
        <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm text-slate-600">ကော်မရှင်<select name="commission_id" defaultValue={commissions[0]?.id} className="mt-1.5 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none focus:border-blue-500">{commissions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm text-slate-600">အကြိမ်<select name="draw_period_id" defaultValue={periods[0]?.id} className="mt-1.5 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none focus:border-blue-500">{periods.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>
        <label className="block text-sm text-slate-600">ဂဏန်းနှင့် ပမာဏ<textarea ref={inputRef} name="raw_input" value={rawInput} onChange={(event) => setRawInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); formRef.current?.requestSubmit(); } }} rows={5} placeholder={"ဥပမာ\nA100\n123R100\n456 200"} className="mt-1.5 w-full resize-y rounded-lg border border-slate-300 px-3 py-3 text-base leading-7 outline-none placeholder:text-slate-400 focus:border-blue-500" /></label>
        <p className="text-xs text-slate-500">`A100` = 000 မှ 999 ထိ အပူးဂဏန်းများ။ `123R100` = 123 ရဲ့ digit permutation များ။</p>
        {state.error && <p className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{state.error}</p>}{state.success && <p className="rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{state.success}</p>}
        <p className="text-xs font-medium text-slate-500">Enter = စာရင်းသိမ်းမည် · Shift + Enter = line အသစ်</p>
      </form>
      <div className="mt-6 border-t border-slate-200 pt-5"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">အရောင်းစာရင်း</h3><span className="text-sm text-slate-500">နောက်ဆုံးထည့်ထားသည်များ</span></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-3 py-2">#</th><th className="px-3 py-2">စာရင်း</th><th className="px-3 py-2 text-right">စုစုပေါင်း</th><th className="px-3 py-2">အချိန်</th><th className="px-3 py-2 text-center">အသေးစိတ်</th><th className="px-3 py-2 text-center">ဖျက်ရန်</th></tr></thead><tbody>{sales.map((sale) => { const expanded = expandedSales.has(sale.id); return <Fragment key={sale.id}><tr className="border-b border-slate-100"><td className="px-3 py-3 text-slate-500">{sale.receipt_number}</td><td className="max-w-[260px] truncate px-3 py-3">{sale.raw_input}</td><td className="px-3 py-3 text-right font-semibold">{formatMoney(Number(sale.total_amount))}</td><td className="px-3 py-3 text-xs text-slate-500">{new Date(sale.created_at).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}</td><td className="px-3 py-3 text-center"><button type="button" onClick={() => setExpandedSales((current) => { const next = new Set(current); if (expanded) next.delete(sale.id); else next.add(sale.id); return next; })} className="rounded-md border border-slate-200 px-2 py-1 text-xs text-blue-700 hover:bg-blue-50">{expanded ? "ဖျောက်" : "ကြည့်"}</button></td><td className="px-3 py-3 text-center"><form action={deleteSale}><input type="hidden" name="sale_id" value={sale.id} /><button type="submit" onClick={(event) => { if (!window.confirm("ဒီအရောင်းစာရင်းကို ဖျက်မလား? History ထဲမှာတော့ သိမ်းထားပါမယ်။")) event.preventDefault(); }} aria-label="အရောင်းစာရင်းဖျက်ရန်" className="rounded-md border border-red-200 px-2 py-1 text-xs text-red-600 hover:bg-red-50">ဖျက်</button></form></td></tr>{expanded && <tr className="border-b border-slate-200 bg-slate-50"><td colSpan={6} className="px-4 py-3"><div className="flex flex-wrap gap-2">{sale.items.map((item, index) => <span key={`${item.number}-${index}`} className="rounded-md border border-slate-200 bg-white px-2.5 py-1.5 text-xs text-slate-700"><b>{item.number}</b><span className="mx-1 text-slate-300">-</span>{formatMoney(Number(item.amount))}</span>)}</div></td></tr>}</Fragment>; })}{!sales.length && <tr><td colSpan={6} className="px-3 py-8 text-center text-slate-400">အရောင်းစာရင်း မရှိသေးပါ</td></tr>}</tbody></table></div></div>
    </section>
    <aside className="space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">ဂဏန်းအလိုက် ရောင်းအား</h2><p className="mt-1 text-xs text-slate-500">{prefix}00 – {prefix}99</p></div><div className="flex items-center gap-1"><button type="button" onClick={() => setPrefix((value) => (value + 9) % 10)} aria-label="ယခင်ရှေ့ဂဏန်း" className="h-7 w-7 rounded-md border border-slate-300 text-sm text-slate-600 hover:bg-slate-50">‹</button><span className="min-w-7 text-center text-lg font-bold text-blue-700">{prefix}</span><button type="button" onClick={() => setPrefix((value) => (value + 1) % 10)} aria-label="နောက်ရှေ့ဂဏန်း" className="h-7 w-7 rounded-md border border-slate-300 text-sm text-slate-600 hover:bg-slate-50">›</button></div></div><div className="mt-3 grid grid-cols-4 overflow-hidden rounded-lg border border-slate-200">{numbers.map((number) => <button type="button" key={number} onClick={() => addNumberToInput(number)} title={`${number} ကို input ထဲထည့်ရန်`} className={`flex min-h-10 items-baseline justify-between gap-1 whitespace-nowrap border-b border-r border-slate-200 px-2 py-1.5 text-left transition hover:bg-blue-50 active:bg-blue-100 ${numberTotals[number] ? "bg-blue-50/60" : "bg-white"}`}><span className={`text-[13px] leading-none ${numberTotals[number] ? "font-bold text-blue-800" : "font-semibold text-slate-800"}`}>{number}</span><span className={`text-[11px] leading-none ${numberTotals[number] ? "font-semibold text-blue-700" : "text-slate-400"}`}>- {numberTotals[number] ? formatMoney(numberTotals[number]) : "0"}</span></button>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">အနှစ်ချုပ်</h2><span className="text-xs text-slate-500">ယခုအကြိမ်</span></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-lg bg-blue-50 p-3"><p className="text-xs text-blue-700">စာရင်းအရေအတွက်</p><p className="mt-1 text-xl font-bold text-blue-900">{formatMoney(sales.length)}</p></div><div className="rounded-lg bg-emerald-50 p-3"><p className="text-xs text-emerald-700">စုစုပေါင်းရောင်းအား</p><p className="mt-1 text-xl font-bold text-emerald-900">{formatMoney(sales.reduce((sum, sale) => sum + Number(sale.total_amount), 0))}</p></div></div></section></aside>
  </div>;
}
