"use client";

import { useActionState } from "react";
import { createCommission, createDrawPeriod } from "@/app/actions/setup";

export default function Setup({ showCommission, showPeriod }: { showCommission: boolean; showPeriod: boolean }) {
  const [commissionState, commissionAction, commissionPending] = useActionState(createCommission, {});
  const [periodState, periodAction, periodPending] = useActionState(createDrawPeriod, {});
  if (!showCommission && !showPeriod) return null;
  return <section className="mb-5 rounded-xl border border-amber-200 bg-amber-50/70 p-4 shadow-sm"><div className="mb-3"><h2 className="font-bold text-amber-950">စတင်အသုံးပြုရန် setup လုပ်ပါ</h2><p className="mt-1 text-xs text-amber-800">အရောင်းစာရင်းသိမ်းရန် ကော်မရှင်လူနဲ့ အကြိမ် အနည်းဆုံးတစ်ခုစီလိုပါတယ်။</p></div><div className="grid gap-4 lg:grid-cols-2">{showCommission && <form action={commissionAction} className="rounded-lg border border-amber-200 bg-white p-4"><h3 className="mb-3 text-sm font-semibold">ကော်မရှင်လူအသစ်</h3><div className="grid gap-2 sm:grid-cols-2"><input name="name" required placeholder="အမည်" className="h-9 rounded-md border border-slate-300 px-3 text-sm" /><input name="phone" placeholder="ဖုန်း (optional)" className="h-9 rounded-md border border-slate-300 px-3 text-sm" /><input name="commission_percent" type="number" min="0" max="100" defaultValue="0" placeholder="ကော်မရှင် %" className="h-9 rounded-md border border-slate-300 px-3 text-sm" /><input name="default_payout_rate" type="number" min="0" defaultValue="80" placeholder="ပေါက်နှုန်း" className="h-9 rounded-md border border-slate-300 px-3 text-sm" /></div><button disabled={commissionPending} className="mt-3 h-9 rounded-md bg-blue-700 px-4 text-sm font-semibold text-white disabled:bg-slate-300">{commissionPending ? "သိမ်းနေသည်…" : "ကော်မရှင်ထည့်မည်"}</button>{commissionState.error && <p className="mt-2 text-xs text-red-700">{commissionState.error}</p>}{commissionState.success && <p className="mt-2 text-xs text-emerald-700">{commissionState.success}</p>}</form>}{showPeriod && <form action={periodAction} className="rounded-lg border border-amber-200 bg-white p-4"><h3 className="mb-3 text-sm font-semibold">အကြိမ်အသစ်</h3><input name="name" required placeholder="အကြိမ်အမည် (ဥပမာ - September 1st)" className="h-9 w-full rounded-md border border-slate-300 px-3 text-sm" /><div className="mt-2 grid gap-2 sm:grid-cols-3"><label className="text-[11px] text-slate-500">စတင်ရက်<input name="start_date" type="date" required className="mt-1 h-9 w-full rounded-md border border-slate-300 px-2 text-xs" /></label><label className="text-[11px] text-slate-500">ပြီးဆုံးရက်<input name="end_date" type="date" required className="mt-1 h-9 w-full rounded-md border border-slate-300 px-2 text-xs" /></label><label className="text-[11px] text-slate-500">ပေါက်မည့်ရက်<input name="draw_date" type="date" required className="mt-1 h-9 w-full rounded-md border border-slate-300 px-2 text-xs" /></label></div><button disabled={periodPending} className="mt-3 h-9 rounded-md bg-blue-700 px-4 text-sm font-semibold text-white disabled:bg-slate-300">{periodPending ? "သိမ်းနေသည်…" : "အကြိမ်ထည့်မည်"}</button>{periodState.error && <p className="mt-2 text-xs text-red-700">{periodState.error}</p>}{periodState.success && <p className="mt-2 text-xs text-emerald-700">{periodState.success}</p>}</form>}</div></section>;
}
